image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - k8s-deploy-canary
  - k8-deploy

variables:
  PROJECT: shortaner
  CI_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CI_REGISTRY/sadeghhayeri/shortaner:$CI_COMMIT_REF_SLUG
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-shortaner:
  stage: build
  tags:
    - docker
  script:
    - ls
    - cd src
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test-shoraner:
  stage: test
  tags:
    - docker
  only:
    - production
  script:
    - echo 'deploy!'
