image: docker:latest

stages:
  - build
  - test
  - k8s-deploy-canary
  - k8-deploy

variables:
  PROJECT: shortaner
  CI_REGISTRY: dregistry.gitlab.com
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAME
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-shortaner:
  stage: build
  tags:
    - docker
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push CONTAINER_IMAGE

test-shoraner:
  stage: test
  tags:
    - docker
  only:
    - production
  script:
    - echo 'deploy!'
