stages:
  - build
  - k8-deploy
  - test
  - k8s-deploy-canary

variables:
  PROJECT: shortener
  CI_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CI_REGISTRY/sadeghhayeri/shortener/app:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375

build-shortener:
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd src
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

deploy-k8-shortener:
  stage: k8-deploy
  tags:
    - k8-deployer
  script:
    - which kubectl
    - kubectl version
#    - mkdir -p ~/.kube
#    - echo $KUBE_CONFIG > ~/.kube/config
#    - kubectl set image deployment/shortener shortener=$CONTAINER_IMAGE --record
