stages:
  - build
  - test
  - k8s-deploy-canary
  - k8-deploy

variables:
  PROJECT: shortaner
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: registry.gitlab.com/shortaner
  CONTAINER_IMAGE: registry.gitlab.com/shortaner:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-shortaner:
  stage: build
  tags:
    - docker
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test-shoraner:
  stage: test
  tags:
    - docker
  only:
    - production
  script:
    - echo 'deploy!'
