image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - k8s-deploy-canary
  - k8-deploy

variables:
  PROJECT: shortener
  CI_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CI_REGISTRY/sadeghhayeri/shortener/app:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build-shortener:
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd src
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

deploy-k8-shortener:
  stage: k8-deploy
  tags:
    - kubectl
  script:
    - mkdir ~/.kube/config
    - echo $KUBE_CONFIG > ~/.kube/config
    - kubectl set image deployment/shortener shortener=$CONTAINER_IMAGE --record
