gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "aynmLfcKEkXs3ncbHyeZ"
concurrent: 3
checkInterval: 10

rbac:
  create: true
  clusterWideAccess: true

metrics:
  enabled: true

runners:
  image: docker:19.03.8
  privileged: true
  tags: "docker"

  builds:
    cpuRequests: 50m
    memoryRequests: 50Mi
  services:
    cpuRequests: 50m
    memoryRequests: 50Mi
  helpers:
    cpuRequests: 50m
    memoryRequests: 50Mi