gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "aynmLfcKEkXs3ncbHyeZ"
concurrent: 1
checkInterval: 10

rbac:
  create: true
  clusterWideAccess: true

metrics:
  enabled: true

runners:
  image: registry.gitlab.com/sadeghhayeri/shortener/deployer
  privileged: true
  tags: "k8-deployer"

  builds:
    cpuRequests: 50m
    memoryRequests: 50Mi
  services:
    cpuRequests: 50m
    memoryRequests: 50Mi
  helpers:
    cpuRequests: 50m
    memoryRequests: 50Mi