- hosts: all
  become: yes
  tasks:
    - name: create the 'invoker' user
      user: name=invoker append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'invoker' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'invoker ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the invoker user
      authorized_key: user=invoker key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
