const codeStrings = {
    FORBIDDEN: 'FORBIDDEN',
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    DUPLICATE_PATH_ERROR: 'DUPLICATE_PATH_ERROR',
    LINK_NOT_FOUND: 'LINK_NOT_FOUND',
    USERNAME_OR_EMAIL_ALREADY_EXIST: 'USERNAME_OR_EMAIL_ALREADY_EXIST',
    EMAIL_ADDRESS_ALREADY_EXIST: 'EMAIL_ADDRESS_ALREADY_EXIST',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_REQUEST: 'INVALID_REQUEST',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

module.exports = codeStrings;
