const codeStrings = {
    FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    DUPLICATE_PATH_ERROR: 'DUPLICATE_PATH_ERROR',
    LINK_NOT_FOUND: 'LINK_NOT_FOUND',
};

module.exports = codeStrings;
