apiVersion: v1
kind: Service
metadata:
  name: shortener
spec:
  type: LoadBalancer
  selector:
    app: shortener
  externalIPs:
    - 185.206.93.12
    - 185.206.93.13
  ports:
    - port: 8000
      targetPort: 8000
