- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: configure name servers
    shell: |
      echo 'nameserver 185.51.200.2' > /etc/resolv.conf
      echo 'nameserver 178.22.122.100' >> /etc/resolv.conf
